### PR TITLE
add poll feature into agora eEducation app

### PR DESCRIPTION
**Pull request by ashu-saini-bs**
1. Polls can be created only for small-class and lecture-hall.
2. Only Teachers can create polls.
3. Students joined the classroom can vote on the poll created by the teacher.
4. Teachers can download the report of poll result in JSON format.
5. Only one poll can be created a time to create another poll teachers have to end their existing poll. 
6. Once the poll is ended by the teacher the Poll will be destroyed. 
7. The Poll will remain active until 
    (a) teacher is not ending the Poll,  
    (b) his/her session is not destroyed.

### CODE REVIEW

**Comment by Matrixbirds** [comment]
Hello @ashu-saini-bs thx for your contribute, I m testing your poll feature, I got some edge case.
1. I need create poll before student or audience join the classroom page.
2. Student finished the option cannot undo and the teacher side won't get any notice in teacher side UI.
3. I can't replay this poll in replay page.

**Comment by ashu-saini-bs** [comment]
Hello @Matrixbirds thax for your feedback. please look into these points based on your feedback.

For #1

The specific ask/requirement was to create polls on the fly during the class, depending on what the teacher is teaching and the feedback or reaction that the teacher might be getting from the class.

For #2

Undo-ing the response was not a feature requirement or request since the requirement was only to showcase the capability to administer polls using RTM.

For #3

Please provide more clarifications.

**Comment by ashu-saini-bs** [comment]
Hi @Matrixbirds, Can you please guide me how to put/update version for this work?

**Comment by Matrixbirds** [comment]
@ashu-saini-bs I have already sync this infomation with my colleague, we will plain to integrate ask/quiz after the future version, because we are developing the new version with our backend services.

**Pull request closed without merging**
